server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?serverTimezone=UTC
    username: root
    password: 123456
  redis:
    database: 15
    host: 127.0.0.1
    port: 6379
    # 配置使用的缓存：redis
    cache:
      type: redis
upload:
  path: C:/Users/huangxiaolong/Desktop/demo/
token:
  key: "12345678"
manager:
  userName: "admin"



